/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev at Mon Sep  3 10:50:29 2018. */

#ifndef PB_PB_MESSAGES_PB_H_INCLUDED
#define PB_PB_MESSAGES_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _pb_ReceiveControl {
    float temp_set_far;
    float temp_set_cel;
    bool set_on;
    int32_t time_off;
/* @@protoc_insertion_point(struct:pb_ReceiveControl) */
} pb_ReceiveControl;

typedef struct _pb_SendTemp {
    pb_callback_t device_id;
    bool on;
    float temp_cel;
    float temp_far;
    int32_t time;
/* @@protoc_insertion_point(struct:pb_SendTemp) */
} pb_SendTemp;

/* Default values for struct fields */

/* Initializer values for message structs */
#define pb_SendTemp_init_default                 {{{NULL}, NULL}, 0, 0, 0, 0}
#define pb_ReceiveControl_init_default           {0, 0, 0, 0}
#define pb_SendTemp_init_zero                    {{{NULL}, NULL}, 0, 0, 0, 0}
#define pb_ReceiveControl_init_zero              {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define pb_ReceiveControl_temp_set_far_tag       1
#define pb_ReceiveControl_temp_set_cel_tag       2
#define pb_ReceiveControl_set_on_tag             3
#define pb_ReceiveControl_time_off_tag           4
#define pb_SendTemp_device_id_tag                1
#define pb_SendTemp_on_tag                       2
#define pb_SendTemp_temp_cel_tag                 3
#define pb_SendTemp_temp_far_tag                 4
#define pb_SendTemp_time_tag                     5

/* Struct field encoding specification for nanopb */
extern const pb_field_t pb_SendTemp_fields[6];
extern const pb_field_t pb_ReceiveControl_fields[5];

/* Maximum encoded size of messages (where known) */
/* pb_SendTemp_size depends on runtime parameters */
#define pb_ReceiveControl_size                   23

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MESSAGES_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
