/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Mon Sep  3 10:50:29 2018. */

#include "messages.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t pb_SendTemp_fields[6] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, pb_SendTemp, device_id, device_id, 0),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, pb_SendTemp, on, device_id, 0),
    PB_FIELD(  3, FLOAT   , SINGULAR, STATIC  , OTHER, pb_SendTemp, temp_cel, on, 0),
    PB_FIELD(  4, FLOAT   , SINGULAR, STATIC  , OTHER, pb_SendTemp, temp_far, temp_cel, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, pb_SendTemp, time, temp_far, 0),
    PB_LAST_FIELD
};

const pb_field_t pb_ReceiveControl_fields[5] = {
    PB_FIELD(  1, FLOAT   , SINGULAR, STATIC  , FIRST, pb_ReceiveControl, temp_set_far, temp_set_far, 0),
    PB_FIELD(  2, FLOAT   , SINGULAR, STATIC  , OTHER, pb_ReceiveControl, temp_set_cel, temp_set_far, 0),
    PB_FIELD(  3, BOOL    , SINGULAR, STATIC  , OTHER, pb_ReceiveControl, set_on, temp_set_cel, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, pb_ReceiveControl, time_off, set_on, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
